# docker-compose.yml - ОБНОВЛЕННАЯ с reports volume
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: car_monitor
      MYSQL_USER: caruser
      MYSQL_PASSWORD: carpass
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+aiomysql://caruser:carpass@mysql:3306/car_monitor
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
      - html_reports:/app/reports  # НОВЫЙ: для сохранения HTML отчетов
      - app_logs:/app/logs         # НОВЫЙ: для логов

volumes:
  mysql_data:
  html_reports:  # НОВЫЙ: для HTML отчетов
  app_logs:      # НОВЫЙ: для логов