"""Initial migration with detailed car fields

Revision ID: 8a7603c27eb5
Revises: 
Create Date: 2025-05-31 21:15:57.020377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7603c27eb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.String(length=100), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('filter_name', sa.String(length=50), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mot_till', sa.String(length=50), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('gearbox', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('engine_size', sa.String(length=50), nullable=True),
    sa.Column('doors', sa.String(length=20), nullable=True),
    sa.Column('seats', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('previous_owners', sa.String(length=20), nullable=True),
    sa.Column('registration', sa.String(length=100), nullable=True),
    sa.Column('import_duty_paid', sa.String(length=20), nullable=True),
    sa.Column('roadworthy_certificate', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seller_type', sa.String(length=50), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('details_parsed', sa.Boolean(), nullable=True),
    sa.Column('details_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_characteristics', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_brand'), 'cars', ['brand'], unique=False)
    op.create_index(op.f('ix_cars_filter_name'), 'cars', ['filter_name'], unique=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_link'), 'cars', ['link'], unique=True)
    op.create_index(op.f('ix_cars_mileage'), 'cars', ['mileage'], unique=False)
    op.create_index(op.f('ix_cars_year'), 'cars', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_mileage'), table_name='cars')
    op.drop_index(op.f('ix_cars_link'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_filter_name'), table_name='cars')
    op.drop_index(op.f('ix_cars_brand'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
