"""Add changes tracking fields to cars table

Revision ID: tracking_changes_001
Revises: 8a7603c27eb5
Create Date: 2025-01-14 12:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'tracking_changes_001'
down_revision: Union[str, None] = '8a7603c27eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые поля для отслеживания изменений
    op.add_column('cars', sa.Column('previous_price', sa.String(length=100), nullable=True))
    op.add_column('cars', sa.Column('previous_description', sa.Text(), nullable=True))
    op.add_column('cars', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('cars', sa.Column('price_changed_at', sa.DateTime(), nullable=True))
    op.add_column('cars', sa.Column('description_changed_at', sa.DateTime(), nullable=True))
    op.add_column('cars', sa.Column('price_changes_count', sa.Integer(), nullable=True, default=0))
    op.add_column('cars', sa.Column('description_changes_count', sa.Integer(), nullable=True, default=0))

    # Создаем индексы для эффективных запросов
    op.create_index('ix_cars_last_checked_at', 'cars', ['last_checked_at'])
    op.create_index('ix_cars_price_changed_at', 'cars', ['price_changed_at'])
    op.create_index('ix_cars_description_changed_at', 'cars', ['description_changed_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы
    op.drop_index('ix_cars_description_changed_at', 'cars')
    op.drop_index('ix_cars_price_changed_at', 'cars')
    op.drop_index('ix_cars_last_checked_at', 'cars')

    # Удаляем добавленные поля
    op.drop_column('cars', 'description_changes_count')
    op.drop_column('cars', 'price_changes_count')
    op.drop_column('cars', 'description_changed_at')
    op.drop_column('cars', 'price_changed_at')
    op.drop_column('cars', 'last_checked_at')
    op.drop_column('cars', 'previous_description')
    op.drop_column('cars', 'previous_price')
    # ### end Alembic commands ###